SampleProject/SampleProject/Controllers/ActionTaskController.cs
using SampleProject.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleProject.Controllers
{
    public class ActionTaskController : BaseController
    {
        //
        // GET: /ActionTask/
        [AuthorizeRoles(Roles = "Administrator")]
        public ActionResult AdministratorAction()
        {
            return View();
        }

        [AuthorizeRoles(Roles = "Teacher")]
        public ActionResult TeacherAction()
        {
            return View();
        }
	}
}

SampleProject/SampleProject/Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Model;
using SampleProject.Core;
using SampleProject.Models;
using Service;
using Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace SampleProject.Controllers
{
    public class HomeController : BaseController
    {
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            if (User.Identity.IsAuthenticated && User.Identity.GetUserName() != string.Empty)
            {
                return RedirectToLocal(string.Empty);
            }

            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserLoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IUserCredentialService service = GetUserCredentialService();
                var user = service.Get(model.Email);
                if (user != null)
                {
                    if (StringCipher.Decrypt(user.UserPassword) != model.Password)
                    {
                        ModelState.AddModelError("", "Invalid username or password.");
                    }
                    else
                    {
                        SignIn(user.UserInformation, model.RememberMe);
                        return RedirectToLocal(returnUrl);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Invalid username or password.");
                }

            }
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            ViewBag.UserTypes = GetUserTypes();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Register(UserRegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userCredential = new List<UserCredential>();
                    userCredential.Add(new UserCredential()
                    {
                        Email = model.Email,
                        UserPassword = StringCipher.Encrypt(model.Password)
                    });

                    var userInformation = new UserInformation()
                    {
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        Email = model.Email,
                        UserTypeId = model.UserTypeId,
                        UserCredentials = userCredential
                    };

                    IUserInformationService service = GetUserInformationService();
                    service.Add(userInformation);
                    service.Save();

                    var credentialInfo = GetUserCredentialService();
                    var info = credentialInfo.Get(model.Email);
                    SignIn(info.UserInformation, false);

                    return RedirectToLocal(string.Empty);

                }
                catch (System.Data.Entity.Infrastructure.DbUpdateException ex)
                {
                    var sqlException = ex.GetBaseException() as System.Data.SqlClient.SqlException;
                    if (sqlException != null)
                    {
                        if (sqlException.Errors.Count > 0)
                        {
                            switch (sqlException.Errors[0].Number)
                            {
                                case 2627:  // Unique constraint error
                                case 2601: // Duplicated key row error
                                    ModelState.AddModelError("", "Email already exists.");
                                    break;
                                default:
                                    throw;
                            }
                        }
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (Exception)
                {
                    throw;
                }
            }

            ViewBag.UserTypes = GetUserTypes();
            return View(model);
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(PasswordChangeViewModel model)
        {
            if (ModelState.IsValid)
            {
                IUserCredentialService service = GetUserCredentialService();
                var user = service.Get(User.Identity.GetUserName());

                var oldDecryptPassword = StringCipher.Decrypt(user.UserPassword);
                if (oldDecryptPassword != model.OldPassword)
                {
                    ModelState.AddModelError("", "Old password do not match.");
                }
                else
                {
                    var newEncryptedpassword = StringCipher.Encrypt(model.NewPassword);
                    user.UserPassword = newEncryptedpassword;

                    service.UpdateUserCredential(user);
                    service.Save();
                    return RedirectToLocal(string.Empty);                    
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            AuthenticationManager.SignOut();
            return RedirectToAction("Login", "Home");
        }

        [AllowAnonymous]
        public ActionResult AccessDenied()
        {
            return View();
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        private void SignIn(UserInformation user, bool isPersistent)
        {
            var identity = new[]{ 
              // adding following 2 claim just for supporting default antiforgery provider
              new Claim(ClaimTypes.NameIdentifier, user.Email),
              new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", "ASP.NET Identity", "http://www.w3.org/2001/XMLSchema#string"),
              new Claim(ClaimTypes.Name, user.Email),
              new Claim(ClaimTypes.Actor, user.FirstName.Trim() + " " + user.LastName.Trim()),
              new Claim(ClaimTypes.PrimarySid, user.UserInformationId.ToString()),
              new Claim(ClaimTypes.Role, user.UserType.TypeName)
          };
            var claimIdentity = new ClaimsIdentity(identity, DefaultAuthenticationTypes.ApplicationCookie);

            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);
            AuthenticationManager.SignIn(new AuthenticationProperties { IsPersistent = isPersistent }, claimIdentity);

        }

        private IUserCredentialService GetUserCredentialService()
        {
            Data.IDbFactory dbFactory = new Data.DbFactory();
            Data.IUnitOfWork iUnitOfWork = new Data.UnitOfWork(dbFactory);
            Data.IUserCredentialRepository iUserCredentialRepository = new Data.UserCredentialRepository(dbFactory);
            return new UserCredentialService(iUserCredentialRepository, iUnitOfWork);
        }

        private IUserTypeService GetUserTypeService()
        {
            Data.IDbFactory dbFactory = new Data.DbFactory();
            Data.IUserTypeRepository iUserCredentialRepository = new Data.UserTypeRepository(dbFactory);
            return new UserTypeService(iUserCredentialRepository);
        }

        private IUserInformationService GetUserInformationService()
        {
            Data.IDbFactory dbFactory = new Data.DbFactory();
            Data.IUnitOfWork iUnitOfWork = new Data.UnitOfWork(dbFactory);
            Data.IUserInformationRepository iUserCredentialRepository = new Data.UserInformationRepository(dbFactory);
            return new UserInformationService(iUserCredentialRepository, iUnitOfWork);
        }


        private List<UserType> GetUserTypes()
        {
            IUserTypeService service = GetUserTypeService();
            return service.Get();
        }
    }
}

SampleProject/SampleProject/Views/Home/AccessDenied.cshtml
@{
    ViewBag.Title = "Access Denied";
}
<div class="content-holder">
    <div class="content-title">
        <h3>@ViewBag.Title</h3>
    </div>
    You do not have permission to view the page.
</div>

SampleProject/SampleProject/Views/Home/ChangePassword.cshtml
@model SampleProject.Models.PasswordChangeViewModel

@{
    ViewBag.Title = "ChangePassword";
}

<h2>ChangePassword</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PasswordChangeViewModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.OldPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OldPassword)
                @Html.ValidationMessageFor(model => model.OldPassword)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPassword)
                @Html.ValidationMessageFor(model => model.NewPassword)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword)
                @Html.ValidationMessageFor(model => model.ConfirmPassword)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SampleProject/SampleProject/Views/Home/Index.cshtml
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">Sample Project in ASP.NET MVC framework.</p>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>Administartor Access Only</h2>
        <p>
            Only Administrator can view this page after authentication.
        </p>
        <p>
            @Html.ActionLink("Click Here", "AdministratorAction", "ActionTask", null, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2>Teacher Access Only</h2>
        <p>Only Teacher can view this page after authentication.</p>
        <p>
            @Html.ActionLink("Click Here", "TeacherAction", "ActionTask", null, new { @class = "btn btn-default" })
        </p>
    </div>
    @if (Request.IsAuthenticated)
    {
        <div class="col-md-4">
            <h2>Get User Id from Api</h2>
            <p>Click to get User id from api.</p>
            <p>
                <button onclick="myfunction();" class="btn btn-default">Click Here</button>
            </p>
        </div>
    }
</div>
@section scripts{
    <script>
        function myfunction() {
            $.ajax({
                url: '/Api/Common/GetUserId',
                method: 'GET',
                success: function (data) {
                    alert(data);
                }
            });
        }
    </script>
}

SampleProject/SampleProject/Views/Home/Login.cshtml
@model SampleProject.Models.UserLoginViewModel

@{
    ViewBag.Title = "Log in";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Home", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register", "Register") if you don't have a local account.
                </p>
            }
        </section>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SampleProject/SampleProject/Views/Home/Register.cshtml
@model SampleProject.Models.UserRegisterViewModel

@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="col-md-7">
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-3" })
                <div class="col-md-5">
                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-3" })
                <div class="col-md-5">
                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-3" })
                <div class="col-md-5">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserTypeId, new { @class = "control-label col-md-3" })
                <div class="col-md-5">
                    @Html.DropDownListFor(model => model.UserTypeId, new SelectList(ViewBag.UserTypes, "UserTypeId", "TypeName"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserTypeId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-3" })
                <div class="col-md-5">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-3" })
                <div class="col-md-5">
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}